# Generated by Django 2.2.5 on 2019-10-28 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='비디오')),
                ('playlist', models.IntegerField(verbose_name='비디오 개수')),
                ('description', models.TextField(verbose_name='비디오 설명')),
                ('register_date', models.DateTimeField(auto_now_add=True, verbose_name='등록날짜')),
                ('path', models.CharField(max_length=60, null=True)),
            ],
            options={
                'verbose_name': '비디오',
                'verbose_name_plural': '비디오',
                'db_table': 'video',
            },
        ),
    ]
