# Generated by Django 2.2.5 on 2019-11-03 14:49

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('video', '0001_initial'),
        ('analyzer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_image',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=512),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Reaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reaction', models.CharField(max_length=512)),
                ('register_date', models.DateTimeField(auto_now_add=True, verbose_name='등록날짜')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.READ_User', verbose_name='사용자')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='video.Video', verbose_name='비디오')),
            ],
        ),
    ]
